<?php /** @var $this IntegerNet_MagentoLocalized_Block_Frontend_Copyright */ ?>

<p>
    <?php $localeCode = Mage::app()->getLocale()->getLocaleCode() ?>
    <?php echo Mage::helper('magento_localized')->__('<a href="%s" target="_blank">%s</a> este un proiect al comunității Magento ',
        'http://www.nr-apps.com/store/magento-ro.html',
        'Magento RO'
    ) ?>
    <?php echo Mage::helper('magento_localized')->__('powered by') ?>
    <?php echo Mage::helper('magento_localized')->__('<a href="%s" target="_blank">Netresearch App Factory</a>, <a href="%s" target="_blank">integer_net</a> &amp; <a href="%s" target="_blank">MindMagnet</a>.',
        'http://www.nr-apps.com',
        'http://www.integer-net.de',
        'http://www.mindmagnetsoftware.com'
    ) ?>
</p>
